INITIAL_EXTENSIONS = [
    "cogs.drive",
    "cogs.errors.handler",
    "cogs.events",
    "cogs.help",
    "cogs.ign",
    "cogs.info",
    "cogs.logger",
    "cogs.mod",
    "cogs.owner",
    "cogs.prefix",
    "cogs.self_roles",
    "cogs.tag",
    "cogs.verification",
    "cogs.VoiceChat",
    "cogs.voltorb",
]
